CREATE TABLE IF NOT EXISTS ExerciseLog (
  id INTEGER NOT NULL PRIMARY KEY  AUTOINCREMENT,
  user_id INTEGER UNSIGNED NOT NULL,
  duration INT NOT NULL,
  date DATE NOT NULL,
  time TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS FoodLog (
  id INTEGER NOT NULL PRIMARY KEY  AUTOINCREMENT,
  user_id INTEGER UNSIGNED NOT NULL,
  date DATE NOT NULL,
  qty INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Goal (
  id INTEGER NOT NULL PRIMARY KEY  AUTOINCREMENT,
  user_id INTEGER UNSIGNED NOT NULL,
  name VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  goalWeight FLOAT NOT NULL,
  startingDate DATE NOT NULL,
  endDate DATE NOT NULL,
  isAchieved BOOL NULL
);

CREATE TABLE  IF NOT EXISTS User (
  id INTEGER NOT NULL PRIMARY KEY  AUTOINCREMENT,
  email VARCHAR NOT NULL,
  password_ VARCHAR NOT NULL
);

CREATE TABLE  IF NOT EXISTS WeightLog (
  id INTEGER NOT NULL PRIMARY KEY  AUTOINCREMENT,
  user_id INTEGER UNSIGNED NOT NULL,
  date DATE NOT NULL,
  weight FLOAT NOT NULL
);


CREATE TABLE  IF NOT EXISTS UserProfile (
  id INTEGER NOT NULL PRIMARY KEY  AUTOINCREMENT,
  firstName VARCHAR NOT NULL,
  lastName VARCHAR NOT NULL,
  profilePicture VARCHAR NULL,
  height FLOAT NOT NULL,
  isMarried BOOL NOT NULL,
  gender CHAR NOT NULL
);